Algoritmo "JuntarNome"

Var
nome1, nome2, nome3, nomecomp: caractere

Inicio
      escreva("Escreva seu primeiro nome: ")
      leia(nome1)
      escreva("Escreva seu sobrenome: ")
      leia(nome2)
      escreva("Escreva seu segundo sobrenome: ")
      leia(nome3)
      
           nomecomp <- nome1 +" " + nome2 +" " + nome3
           
           escreva("Seu nome completo é: " + nomecomp)
      


Fimalgoritmo